version: '3'

services:
  server:
    build: .
    command: /bin/bash -c 'echo OK'
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:8080"
    environment:
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
      TZ: Asia/Tokyo
